from .prompts import (
    _SYSTEM_PROMPT_JUDGE,
    _SYSTEM_PROMPT_ADVISORY,
    _SYSTEM_PROMPT_RESPONSE_ANALYSIS,
    _SYSTEM_PROMPT_BASEURL_RESOLVE,
    _SYSTEM_PROMPT_BASEURL_JUDGE_ROUND,
    _SYSTEM_PROMPT_PREFIX_VERIFY,
)

SYSTEM_PROMPT_JUDGE = _SYSTEM_PROMPT_JUDGE
SYSTEM_PROMPT_ADVISORY = _SYSTEM_PROMPT_ADVISORY
SYSTEM_PROMPT_RESPONSE_ANALYSIS = _SYSTEM_PROMPT_RESPONSE_ANALYSIS
SYSTEM_PROMPT_BASEURL_RESOLVE = _SYSTEM_PROMPT_BASEURL_RESOLVE
SYSTEM_PROMPT_BASEURL_JUDGE_ROUND = _SYSTEM_PROMPT_BASEURL_JUDGE_ROUND
SYSTEM_PROMPT_PREFIX_VERIFY = _SYSTEM_PROMPT_PREFIX_VERIFY

__all__ = [
    'SYSTEM_PROMPT_JUDGE',
    'SYSTEM_PROMPT_ADVISORY',
    'SYSTEM_PROMPT_RESPONSE_ANALYSIS',
    'SYSTEM_PROMPT_BASEURL_RESOLVE',
    'SYSTEM_PROMPT_BASEURL_JUDGE_ROUND',
    'SYSTEM_PROMPT_PREFIX_VERIFY',
]